[project]
name = "radaris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Frederico Engel", email = "181283691+fredmengel@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "certifi>=2026.7.22",
    "httpx>=0.28.1",
    "sqlalchemy>=2.1.4",
]

[project.scripts]
radaris = "radaris:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
